services:
  db:
    image: postgres:15
    container_name: mauzl-db-service
    restart: always
    environment:
      POSTGRES_USER: mauzl_user
      POSTGRES_PASSWORD: mauzl_password
      POSTGRES_DB: mauzl_db
    ports:
      - '5432:5432'
    volumes:
      - mauzl_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: mauzl-minio-service
    restart: unless-stopped
    ports:
      - '9001:9001'
      - '9000:9000'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: 'admin'
      MINIO_ROOT_PASSWORD: 'password'
    command: server --console-address ":9001" /data

volumes:
  mauzl_data:
  minio_data:
