export enum ContactSubject {
  ORDER_STATUS = 'ORDER_STATUS',
  PAYMENT_ISSUES = 'PAYMENT_ISSUES',
  REFUND_RETURN_REQUEST = 'REFUND_RETURN_REQUEST',
  SHIPPING_DELIVERY_PROBLEMS = 'SHIPPING_DELIVERY_PROBLEMS',
  LOGIN_ACCOUNT_ISSUES = 'LOGIN_ACCOUNT_ISSUES',
  OTHER = 'OTHER',
}
