import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Providers } from "./providers";
import { Box } from "@mui/material";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Mauzl App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <Box px={30} py={10}>
            {children}
          </Box>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
