/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Mauzl API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateOrderItemDto {
  productId: number;
  quantity: number;
  size: string;
}
