/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Mauzl API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateContactDto {
  email: string;
  firstName: string;
  lastName: string;
  message: string;
  phoneNumber: string;
  subject: string;
}
