/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Mauzl API
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAddressDto } from "./createAddressDto";
import type { CreateClientDto } from "./createClientDto";
import type { CreateOrderItemDto } from "./createOrderItemDto";

export interface CreateOrderDto {
  address: CreateAddressDto;
  client: CreateClientDto;
  items: CreateOrderItemDto[];
}
