/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Mauzl API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductDto } from "./productDto";

export interface PaginatedProductDto {
  products: ProductDto[];
  /** Total number of products */
  total: number;
}
