/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Mauzl API
 * OpenAPI spec version: 1.0.0
 */

export type ProductsControllerFindAllParams = {
  page?: number;
  limit?: number;
  name?: string;
  minPrice?: number;
  maxPrice?: number;
  categoryId?: number;
  sortBy?: string;
  statuses?: string;
};
