/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Mauzl API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProductDto {
  additionalInfos?: string[];
  categoryId?: number;
  description?: string;
  name?: string;
  price?: number;
  stock?: number;
}
