/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Mauzl API
 * OpenAPI spec version: 1.0.0
 */

export interface UserDto {
  avatarUrl: string;
  birthDate: string;
  email: string;
  firstName: string;
  hashedRefreshToken: string;
  id: number;
  lastName: string;
  phoneNumber: string;
  role: string;
  username: string;
}
