name: Mauzl Docker Build Push Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-publish-mauzl-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mauzl-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hamzahatoch09/mauzl-ui:latest
          platforms: linux/amd64,linux/arm64
          context: ./mauzl-ui
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_CLARITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_CLARITY_PROJECT_ID }}

  build-publish-mauzl-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mauzl-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: hamzahatoch09/mauzl-api:latest
          platforms: linux/amd64,linux/arm64
          context: ./mauzl-api

  deploy-mauzl:
    runs-on: ubuntu-latest
    needs: [build-publish-mauzl-ui, build-publish-mauzl-api] # Waits for the previous jobs to finish

    steps:
      - name: Deploy mauzl-api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/dockerized-mauzl
            docker-compose down
            docker-compose pull
            docker-compose up -d
